//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleFinanceiro.UI.Presentation.Pages.Logados.RecursosHumanos {
    
    
    public partial class ExportaListaFuncionarios {
        
        /// <summary>
        /// btnGeraListaFunc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnGeraListaFunc;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new ControleFinanceiro.UI.Presentation.Pages.Logados.MasterPageMenu Master {
            get {
                return ((ControleFinanceiro.UI.Presentation.Pages.Logados.MasterPageMenu)(base.Master));
            }
        }
    }
}
